version: "3"
services:
  quhwa-gpio:
    build: https://github.com/bodav/node-quhwa-gpio.git
    network_mode: host
    volumes:
      - /sys:/sys
    environment:
      - GPIOPIN=7
      - "WEBHOOKURL=http://localhost:51828/?accessoryId=doorbellSensor&state=true"
  homebridge:
    image: oznu/homebridge:no-avahi-arm32v6
    restart: always
    network_mode: host
    volumes:
      - ./config:/homebridge
    environment:
      - PGID=1000
      - PUID=1000
      - HOMEBRIDGE_CONFIG_UI=1
      - HOMEBRIDGE_CONFIG_UI_PORT=8080
      - HOMEBRIDGE_INSECURE=1
      - HOMEBRIDGE_DEBUG=1
